name: build-and-push-docker

on: workflow_dispatch

jobs:
  push_to_registry:
    name: Build and push docker
    runs-on: ubuntu-20.04

    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.WRITE_CR_PAT }}

      - name: Set outputs
        id: output_variables
        run: |
          echo "::set-output name=cr_pat_user::${{ secrets.CR_PAT_USER }}"
          echo "::set-output name=read_cr_pat::${{ secrets.READ_CR_PAT }}"

      - name: Push to Github Container Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/erdosgames/godot-steam-ci:4.3
            ghcr.io/erdosgames/godot-steam-ci:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
